### ISSUE TITLE
IHM Issue

### ISSUE THREAD

**Issue by davidbiteghethales19** [smariel/PTree#65] opened 2019-06-06 11:28 UTC
If you have an important list of entries, when you create a regulator , you cannot see the field where you are working/typing (it is below, you  need to scroll)

The windows should automatically scroll to the New entry being entered.

**Comment by smariel** [comment] 2019-09-13 21:01
The issue is relevant and dose not seems to be hard to code. It will be included in on of the next versions.

**Closed** 2019-09-15 17:45 UTC
Labels: enhancement
